version: '3.8'
services:
  backend:
    build: backend
    container_name: 'django-back'
    ports:
      - '8000:8000'
  frontend:
    build: frontend
    container_name: 'next-js-front'
    ports:
      - '3000:3000'
  db:
    image: postgres
    container_name: 'postgres-db'
    restart: always
    volumes:
      - db/postgres:/var/lib/postgresql/data
    env_file: ./db/.env
    expose:
      - 5432
