version: '3.8'
services:
  backend:
    build: ./backend
    container_name: 'django-back'
    depends_on: db
    env_file: ./backend/.env
    ports:
      - '8000:8000'
    volumes:
      - ./backend:/app
    networks:
      - front-net
      - back-net
  frontend:
    build: frontend
    container_name: 'next-js-front'
    ports:
      - '3000:3000'
    networks:
      - front-net
  db:
    image: postgres
    container_name: 'postgres-db'
    restart: always
    volumes:
      - db/postgres:/var/lib/postgresql/data
    env_file: ./db/.env
    expose:
      - 5432
    networks:
      - back-net

networks:
  front-net: {}
  back-net: {}
